### ISSUE TITLE
设置了publicPath之后，路径错误

### ISSUE THREAD

**Issue by transtone** [nekocode/antd-dayjs-vite-plugin#2]
如果在 `vite.config.js` 中设置了 `base`，
```js
export default defineConfig({
  base: `/pc-base`,
})
```
则无法调用此插件。显示
`http://localhost:3000/init-dayjs-vite-plugin-entry.js  404 not found `

因为此时的正确路径应该是 `http://localhost:3000/pc-base/init-dayjs-vite-plugin-entry.js`

https://github.com/nekocode/antd-dayjs-vite-plugin/blob/main/src/index.ts#L39

这里是不是要调整一下？

在 webpack 下用 `antd-dayjs-webpack-plugin` 是不需要设置，但使用正常不报错的。

**Comment by nekocode** [comment]
嗯，感谢反馈！今天上午我解决一下

**Comment by nekocode** [comment]
@transtone 可以帮忙测试一下 `1.1.2` 版本是否解决了这个问题么？

**Comment by transtone** [comment]
> @transtone 可以帮忙测试一下 `1.1.2` 版本是否解决了这个问题么？

`1.1.2` 可以用。

**Comment by nekocode** [comment]
@transtone 谢谢🙏
