### ISSUE TITLE
sorry, is that right?

### ISSUE THREAD

**Issue by geekftz** [nekocode/antd-dayjs-vite-plugin#4]
see [App.tsx](https://github.com/nekocode/antd-dayjs-vite-plugin/blob/main/example/src/App.tsx)
```
// in the test project it can not get the registry
import moment from 'moment';
```

**Comment by nekocode** [comment]
> see [App.tsx](https://github.com/nekocode/antd-dayjs-vite-plugin/blob/main/example/src/App.tsx)
> 
> ```
> // in the test project it can not get the registry
> import moment from 'moment';
> ```

First you need to run `npm/yarn install` in the example directory, the moment package is a dependency of the antd library.
