### ISSUE TITLE
搭配使用 vite-plugin-eslint 会有报错

### ISSUE THREAD

**Issue by winfcloud** [nekocode/antd-dayjs-vite-plugin#5]
最小启动模型，vite官方react模板+antd+vite-plugin-eslint

app.jsx里随便启用一个DatePicker
vite.config 配置上 eslint plugin之后 会先校验 init-dayjs-vite-plugin-entry.js，访问不存在 导致报错

没有去深究具体插件运行顺序，不确定是哪边的问题

目前解决方案是 init-dayjs-vite-plugin-entry.js 丢进 eslintignore

**Comment by wkl007** [comment]
有同样的问题

**Comment by nekocode** [comment]
@winfcloud @wkl007 能帮忙测试一下最新的 `1.2.0` 版本是不是修复了这个问题么？

**Comment by wkl007** [comment]
@nekocode 试了下没有问题。

**Comment by nekocode** [comment]
> @nekocode 试了下没有问题。

感谢🙏
