### ISSUE TITLE
antdDayjs is not a function

### ISSUE THREAD

**Issue by imsfc** [nekocode/antd-dayjs-vite-plugin#6]
- Node.js `v18.7.0`
- Vite `v3.0.9`
- antd-dayjs-vite-plugin `v1.1.4`

[Demo](https://stackblitz.com/edit/vitejs-vite-xmw8nq?file=vite.config.ts)

**Comment by hahatulk** [comment]
> * Node.js `v18.7.0`
> * Vite `v3.0.9`
> * antd-dayjs-vite-plugin `v1.1.4`
> 
> [Demo](https://stackblitz.com/edit/vitejs-vite-xmw8nq?file=vite.config.ts)

you can use this plugin temporary
https://www.npmjs.com/package/unplugin-moment-to-dayjs

**Comment by say8425** [comment]
* Node.js v18.7.0
* Vite v3.0.3
* antd-dayjs-vite-plugin v1.2.0

same issue

**Comment by xuhen** [comment]
![image](https://user-images.githubusercontent.com/8892755/196166590-ee17d68d-b665-4d5d-b3a3-e587b340bddb.png)
I find typeof antdDayjs return object. it should return function, so antdDayjs is not function.

**Comment by xuhen** [comment]
> ![image](https://user-images.githubusercontent.com/8892755/196166590-ee17d68d-b665-4d5d-b3a3-e587b340bddb.png) I find typeof antdDayjs return object. it should return function, so antdDayjs is not function.

This  work for me. I figure that  annotation don't match implementation of that function.
